version: '3.9'
services:
  db:
    image: postgres:latest
    volumes: 
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: qerced/foodgram:latest
    volumes:
      - ../data/:/app/data/
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    command: python3 ./test_connection.py
    env_file:
      - ./.env
  frontend:
    image: qerced/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build/:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend

volumes:
  static_value:
  media_value:
  data_value:
